.TH "message_t" 3 "Lun 6 Giu 2016" "Version 1" "SOL - MEMBOX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
message_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Attributi pubblici"

.in +1c
.ti -1c
.RI "\fBmessage_hdr_t\fP \fBhdr\fP"
.br
.ti -1c
.RI "\fBmessage_data_t\fP \fBdata\fP"
.br
.in -1c

.SH "Autore"
.PP 
Generato automaticamente da Doxygen per SOL - MEMBOX a partire dal codice sorgente\&.
