.TH "operation_t" 3 "Lun 6 Giu 2016" "Version 1" "SOL - MEMBOX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
operation_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Attributi pubblici"

.in +1c
.ti -1c
.RI "membox_key_t \fBkey\fP"
.br
.ti -1c
.RI "\fBop_t\fP \fBop\fP"
.br
.ti -1c
.RI "long \fBsize\fP"
.br
.in -1c

.SH "Autore"
.PP 
Generato automaticamente da Doxygen per SOL - MEMBOX a partire dal codice sorgente\&.
