.TH "statistics" 3 "Lun 6 Giu 2016" "Version 1" "SOL - MEMBOX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
statistics \- Struttura dati contenente le informazioni da monitorare\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stats\&.h>\fP
.SS "Attributi pubblici"

.in +1c
.ti -1c
.RI "unsigned long \fBnput\fP"
.br
.ti -1c
.RI "unsigned long \fBnput_failed\fP"
.br
.ti -1c
.RI "unsigned long \fBnupdate\fP"
.br
.ti -1c
.RI "unsigned long \fBnupdate_failed\fP"
.br
.ti -1c
.RI "unsigned long \fBnget\fP"
.br
.ti -1c
.RI "unsigned long \fBnget_failed\fP"
.br
.ti -1c
.RI "unsigned long \fBnremove\fP"
.br
.ti -1c
.RI "unsigned long \fBnremove_failed\fP"
.br
.ti -1c
.RI "unsigned long \fBnlock\fP"
.br
.ti -1c
.RI "unsigned long \fBnlock_failed\fP"
.br
.ti -1c
.RI "unsigned long \fBconcurrent_connections\fP"
.br
.ti -1c
.RI "unsigned long \fBcurrent_size\fP"
.br
.ti -1c
.RI "unsigned long \fBmax_size\fP"
.br
.ti -1c
.RI "unsigned long \fBcurrent_objects\fP"
.br
.ti -1c
.RI "unsigned long \fBmax_objects\fP"
.br
.in -1c
.SH "Descrizione dettagliata"
.PP 
Struttura dati contenente le informazioni da monitorare\&. 

.SH "Autore"
.PP 
Generato automaticamente da Doxygen per SOL - MEMBOX a partire dal codice sorgente\&.
