.TH "smatrix_t" 3 "Dom 5 Giu 2016" "Version 1" "SOL - SPARSE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
smatrix_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sparse\&.h>\fP
.SS "Attributi pubblici"

.in +1c
.ti -1c
.RI "\fBelem_t\fP ** \fBmat\fP"
.br
.ti -1c
.RI "int \fBnrow\fP"
.br
.ti -1c
.RI "int \fBncol\fP"
.br
.in -1c
.SH "Descrizione dettagliata"
.PP 
rappresentazione della matrice sparsa 
.SH "Documentazione dei membri dato"
.PP 
.SS "\fBelem_t\fP** smatrix_t::mat"
puntatore all'array delle righe 
.SS "int smatrix_t::ncol"
numero di colonne 
.SS "int smatrix_t::nrow"
numero di righe 

.SH "Autore"
.PP 
Generato automaticamente da Doxygen per SOL - SPARSE a partire dal codice sorgente\&.
