.TH "sparse_docenti.c" 3 "Lun 6 Giu 2016" "Version 1" "SOL - SPARSE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sparse_docenti.c \- funzioni print smat implementata dai docenti  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'sparse\&.h'\fP
.br

.SS "Funzioni"

.in +1c
.ti -1c
.RI "void \fBprint_smat\fP (FILE *f, \fBsmatrix_t\fP *a)"
.br
.in -1c
.SH "Descrizione dettagliata"
.PP 
funzioni print smat implementata dai docenti 


.PP
\fBAutore:\fP
.RS 4
Docenti Sol Lab 2015/2016 
.RE
.PP

.SH "Documentazione delle funzioni"
.PP 
.SS "void print_smat (FILE * f, \fBsmatrix_t\fP * l)"
stampa la matrice in forma canonica (FORNITA DAI DOCENTI)
.PP
\fBParametri:\fP
.RS 4
\fIl\fP putatore alla matrice da stampare 
.br
\fIf\fP puntatore al file su cui scrivere 
.RE
.PP

.SH "Autore"
.PP 
Generato automaticamente da Doxygen per SOL - SPARSE a partire dal codice sorgente\&.
